In [169]:
#Jyotiprakash Panda 
#Rollno:22052464

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np
print(np.__version__)

2.1.3


In [9]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [11]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [23]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [27]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array(42)
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


1
0
2
3


In [29]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])

2


In [31]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1] + arr[3])


6


In [41]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('4th element on 2nd row is:', arr[1,3])

4th element on 2nd row is: 9


In [43]:
import numpy as np 
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


In [47]:
import numpy as np 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim',arr[-2,-3])

last element from 2nd dim 3


In [55]:
import numpy as np
import time 
import sys

s = range(1000)
print(s[6])

print(sys.getsizeof(6) * len(s))

D = np.arange(1000)
print(D.size * D.itemsize)


6
28000
8000


In [57]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [59]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [61]:
import numpy as np
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [69]:
import numpy as np
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [71]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [73]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [75]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [77]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [79]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [81]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [83]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [93]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2)) 
print(arr)


[1 2 3 4 5 6]


In [101]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2),axis=0) 
print(arr)

[1 2 3 4 5 6]


In [99]:
import numpy as np


arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Number of dimensions:', arr.ndim)


[[[[[1 2 3 4]]]]]
Number of dimensions: 5


In [103]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0) 
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [105]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1) 
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [107]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [113]:
import numpy as np
arr1 = np.arange(1, 11)
print('1D Array of the first 10 natural numbers:', arr1)


1D Array of the first 10 natural numbers: [ 1  2  3  4  5  6  7  8  9 10]


In [115]:
import numpy as np
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_two_columns = arr2[:, :2]
print("First two columns of a 2D array:", first_two_columns)


First two columns of a 2D array: [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [121]:
import numpy as np
arr3 = np.random.random((3, 3))
print("3x3 Array of random numbers:", arr3)
print("Shape of the array:",arr3.shape)

3x3 Array of random numbers: [[0.26453187 0.63786804 0.57401769]
 [0.14278145 0.91175555 0.46485479]
 [0.45108568 0.85263649 0.06676114]]
Shape of the array: (3, 3)


In [123]:
import numpy as np
arr4 = np.arange(1, 17)
reshaped_arr4 = arr4.reshape(4, 4)
print("Reshaped 4x4 matrix:", reshaped_arr4)


Reshaped 4x4 matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [131]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
add = a + b
print("Element-wise addition:",add)
sub = a - b
print("Element-wise subtraction:", sub)
mul = a * b
print("Element-wise multiplication:", mul)
div = a / b
print("Element-wise division:", div)


Element-wise addition: , [ 6  8 10 12]
Element-wise subtraction: [-4 -4 -4 -4]
Element-wise multiplication: [ 5 12 21 32]
Element-wise division: [0.2        0.33333333 0.42857143 0.5       ]


In [135]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10], [11, 12]])
dot_product = np.dot(array1, array2)
print("Dot Product:\n", dot_product)

Dot Product:
 [[ 58  64]
 [139 154]]


In [137]:
import numpy as np
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [147]:
import numpy as np
num = np.arange(1, 21)
even_mask = (num % 2 == 0)
even_numbers = num[even_mask]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10 12 14 16 18 20]


In [149]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
logical_and = array > 3  
logical_or = array < 3   
print("Logical AND (array > 3):", logical_and)
print("Logical OR (array < 3):", logical_or)

Logical AND (array > 3): [False False False  True  True]
Logical OR (array < 3): [ True  True False False False]


In [153]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
concat_rows = np.concatenate((array1, array2), axis=0)
print("Concatenated along rows:\n", concat_rows)
concat_columns = np.concatenate((array1, array2), axis=1)
print("Concatenated along columns:\n", concat_columns)

Concatenated along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along columns:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [155]:
import numpy as np

array = np.arange(20).reshape(10, 2)
split_arrays = np.split(array, 5)
print("Split Arrays:", split_arrays)

Split Arrays: [array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]]), array([[ 8,  9],
       [10, 11]]), array([[12, 13],
       [14, 15]]), array([[16, 17],
       [18, 19]])]


In [157]:
import numpy as np

array_2d = np.array([[1, 2], [3, 4], [5, 6]])
array_1d = np.array([10, 20])
result = array_2d + array_1d
print("Broadcasting Result:\n", result)

Broadcasting Result:
 [[11 22]
 [13 24]
 [15 26]]


In [159]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])
fancy_indexed_array = array[indices]
print("Fancy Indexed Array:", fancy_indexed_array)

Fancy Indexed Array: [10 30 50]


In [167]:
import numpy as np
import time

size = 1000000
array = np.random.rand(size)

start_time = time.time()
sum_numpy = np.sum(array)
numpy_time = time.time() - start_time

start_time = time.time()
sum_loop = 0
for i in array:
    sum_loop += i
loop_time = time.time() - start_time

print("NumPy Sum:", sum_numpy, "Time:", numpy_time)
print("Loop Sum:", sum_loop, "Time:", loop_time)

NumPy Sum: 500073.59524609806 Time: 0.0010046958923339844
Loop Sum: 500073.5952460875 Time: 0.14966416358947754


In [171]:
import numpy as np
import time

array_c = np.array([[1, 2], [3, 4]], order='C')
array_f = np.asfortranarray([[1, 2], [3, 4]])

print("C-style Array:\n", array_c)
print("Fortran-style Array:\n", array_f)

start_time = time.time()
_ = array_c.T
c_time = time.time() - start_time

start_time = time.time()
_ = array_f.T
f_time = time.time() - start_time

print("C-style Transpose Time:", c_time)
print("Fortran-style Transpose Time:", f_time)


C-style Array:
 [[1 2]
 [3 4]]
Fortran-style Array:
 [[1 2]
 [3 4]]
C-style Transpose Time: 0.0
Fortran-style Transpose Time: 0.0


In [173]:
import numpy as np
import time


array = np.random.rand(1000, 1000)
array_c = np.ascontiguousarray(array)
array_f = np.asfortranarray(array)
start_time_c = time.perf_counter()
row_sums_c = array_c.sum(axis=1)
time_c = time.perf_counter() - start_time_c

start_time_f = time.perf_counter()
row_sums_f = array_f.sum(axis=1)
time_f = time.perf_counter() - start_time_f
start_time_c_col = time.perf_counter()
col_sums_c = array_c.sum(axis=0)
time_c_col = time.perf_counter() - start_time_c_col

start_time_f_col = time.perf_counter()
col_sums_f = array_f.sum(axis=0)
time_f_col = time.perf_counter() - start_time_f_col
print("Row-wise operation (sum of rows):")
print(f"C-style layout time: {time_c:.6f} seconds")
print(f"Fortran-style layout time: {time_f:.6f} seconds")

print("\nColumn-wise operation (sum of columns):")
print(f"C-style layout time: {time_c_col:.6f} seconds")
print(f"Fortran-style layout time: {time_f_col:.6f} seconds")

Row-wise operation (sum of rows):
C-style layout time: 0.002874 seconds
Fortran-style layout time: 0.001498 seconds

Column-wise operation (sum of columns):
C-style layout time: 0.001379 seconds
Fortran-style layout time: 0.002579 seconds
